### ISSUE TITLE
Uploading video to Telegram

### ISSUE THREAD

**Issue by 6--** [hieuvts/telegramBot_download_utube#1]
Hello, how to fix this issue?

I get it after downloading video, it wont upload it to telegram.

thanks 

```
args https://youtu.be/TM5VIVvXKxc
Removed old video!
[youtube] TM5VIVvXKxc: Downloading webpage
[download] Destination: video\video.mp4
[download] 100% of 212.64MiB in 00:09
2021-06-18 04:00:29,691 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\p3\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\p3\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\p3\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\p3\lib\http\client.py", line 1047, in _send_output
    self.send(chunk)
  File "C:\p3\lib\http\client.py", line 969, in send
    self.sock.sendall(data)
  File "C:\p3\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\p3\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\p3\lib\site-packages\telegram\utils\request.py", line 253, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\p3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\p3\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\p3\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\p3\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\p3\lib\http\client.py", line 1047, in _send_output
    self.send(chunk)
  File "C:\p3\lib\http\client.py", line 969, in send
    self.sock.sendall(data)
  File "C:\p3\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\p3\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\p3\lib\site-packages\telegram\ext\dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\p3\lib\site-packages\telegram\ext\handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "C:\Users\Administrator\Desktop\telegramBot_download_utube-main\bot.py", line 76, in getVideo
    update.message.reply_video(video=video)
  File "C:\p3\lib\site-packages\telegram\message.py", line 1197, in reply_video
    return self.bot.send_video(
  File "C:\p3\lib\site-packages\telegram\bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "C:\p3\lib\site-packages\telegram\bot.py", line 1081, in send_video
    return self._message(  # type: ignore[return-value]
  File "C:\p3\lib\site-packages\telegram\bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\p3\lib\site-packages\telegram\bot.py", line 259, in _post
    return self.request.post(
  File "C:\p3\lib\site-packages\telegram\utils\request.py", line 348, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "C:\p3\lib\site-packages\telegram\utils\request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out'))
2021-06-18 04:00:40,036 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-06-18 04:00:40,036 - apscheduler.scheduler - INFO - Scheduler has been shut down
```

**Comment by hieuvts** [comment]
@6-- 
Sorry. I didn't mean to public this repo. I'm still developing it.
About your issue. It's the limit of Telegram BOT API. 


***Bots can currently send files of any type of up to 50 MB in size, so yes, very large files won't work for now. Sorry. This limit may be changed in the future.***
https://core.telegram.org/bots/faq

Your video is 212MB.

**Comment by 6--** [comment]
Thank you very much!
